name: enhancerl
channels:
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - bzip2
  - ca-certificates
  - certifi
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - libuuid
  - ncurses
  - openssl
  - pip
  - python
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
    - alembic
    - charset-normalizer
    - class-resolver
    - click
    - click-default-group
    - cmaes
    - colorlog
    - dataclasses-json
    - docdata
    - greenlet
    - idna
    - joblib
    - mako
    - markupsafe
    - marshmallow
    - marshmallow-enum
    - more-click
    - more-itertools
    - mypy-extensions
    - numpy
    - nvidia-cublas-cu11
    - nvidia-cuda-nvrtc-cu11
    - nvidia-cuda-runtime-cu11
    - nvidia-cudnn-cu11
    - optuna
    - packaging
    - pandas
    - protobuf
    - pykeen
    - pystow
    - python-dateutil
    - pytz
    - pyyaml
    - requests
    - rexmex
    - scikit-learn
    - scipy
    - six
    - sklearn
    - sqlalchemy
    - tabulate
    - threadpoolctl
    - torch
    - torch-max-mem
    - torch-ppr
    - tqdm
    - typing-extensions
    - typing-inspect
    - urllib3
