name: secondment
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - backcall
  - blas
  - bottleneck
  - bzip2
  - ca-certificates
  - certifi
  - cudatoolkit
  - debugpy
  - decorator
  - entrypoints
  - ffmpeg
  - freetype
  - giflib
  - gmp
  - gnutls
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - lame
  - lcms2
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libidn2
  - libopus
  - libpng
  - libsodium
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libuv
  - libvpx
  - libwebp
  - libwebp-base
  - lz4-c
  - matplotlib-inline
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nest-asyncio
  - nettle
  - ninja
  - numexpr
  - numpy
  - numpy-base
  - olefile
  - openh264
  - openjdk
  - openssl
  - pandas
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prompt-toolkit
  - ptyprocess
  - pygments
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytz
  - pyzmq
  - readline
  - setuptools
  - six
  - sqlite
  - tk
  - torchaudio
  - torchvision
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - wcwidth
  - wheel
  - x264
  - xz
  - zeromq
  - zlib
  - zstd
  - pip:
    - alembic
    - argon2-cffi
    - attrs
    - autopage
    - beautifulsoup4
    - bleach
    - cffi
    - charset-normalizer
    - class-resolver
    - click
    - click-default-group
    - cliff
    - cmaes
    - cmd2
    - colorama
    - colorlog
    - cycler
    - dataclasses-json
    - deap
    - defusedxml
    - dgl
    - dglke
    - docdata
    - et-xmlfile
    - filelock
    - fonttools
    - gdown
    - greenlet
    - grpcio
    - idna
    - iniconfig
    - ipywidgets
    - isodate
    - jinja2
    - joblib
    - json5
    - jsonschema
    - jupyterlab-pygments
    - jupyterlab-widgets
    - kiwisolver
    - mako
    - markupsafe
    - marshmallow
    - marshmallow-enum
    - matplotlib
    - mistune
    - more-click
    - more-itertools
    - msgpack
    - mypy-extensions
    - nbclient
    - nbconvert
    - nbformat
    - networkx
    - notebook
    - openpyxl
    - optuna
    - owlready2
    - packaging
    - pandocfilters
    - pbr
    - pluggy
    - prettytable
    - prometheus-client
    - protobuf
    - py
    - pycparser
    - pykeen
    - pyparsing
    - pyperclip
    - pyrsistent
    - pysocks
    - pystow
    - pytest
    - python-json-logger
    - pyyaml
    - rdflib
    - reactome2py
    - redis
    - requests
    - scikit-learn
    - scipy
    - seaborn
    - send2trash
    - setuptools-scm
    - sklearn
    - soupsieve
    - sqlalchemy
    - stevedore
    - tabulate
    - terminado
    - testpath
    - threadpoolctl
    - toml
    - tomli
    - tqdm
    - typing-inspect
    - urllib3
    - webencodings
    - widgetsnbextension
    - xlrd
